# Generated by Django 4.0 on 2021-12-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_activation_code_user_activation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activation',
            new_name='activation_code',
        ),
    ]
