# Generated by Django 4.0 on 2021-12-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorites',
        ),
    ]
